### ISSUE TITLE
Support for VS2022 .vsconfig manifests?

### ISSUE THREAD

**Issue by cryticx** [mstorsjo/msvc-wine#163]
I'm _assuming_ that the `.vsconfig` files are what are meant by "manifests", and when I try to use one exported from VS2022, I get the following error:
```
./vsdownload.py --manifest .../.vsconfig
Install packages for x64 host architecture
Traceback (most recent call last):
  File "/home/milan/Downloads/msvc-wine/./vsdownload.py", line 702, in <module>
    packages = getPackages(getManifest(args), args.host_arch)
                           ^^^^^^^^^^^^^^^^^
  File "..././vsdownload.py", line 205, in getManifest
    print("Loaded installer manifest for %s" % (manifest["info"]["productDisplayVersion"]))
                                                ~~~~~~~~^^^^^^^^
KeyError: 'info'
```
and my `.vsconfig` file:
```
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.CoreBuildTools",
    "Microsoft.VisualStudio.Workload.MSBuildTools",
    "Microsoft.VisualStudio.Component.Windows10SDK",
    "Microsoft.VisualStudio.Component.VC.CoreBuildTools",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
    "Microsoft.VisualStudio.Component.TestTools.BuildTools",
    "Microsoft.VisualStudio.Component.VC.ASAN",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.VC.CoreIde",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.Component.Windows11SDK.26100",
    "Microsoft.VisualStudio.Workload.VCTools",
    "Microsoft.VisualStudio.Component.NuGet.BuildTools",
    "Microsoft.Net.Component.4.8.TargetingPack",
    "Microsoft.NetCore.Component.Runtime.8.0",
    "Microsoft.VisualStudio.Wcf.BuildTools.ComponentGroup",
    "Microsoft.Net.Component.4.8.1.SDK",
    "Microsoft.VisualStudio.Component.VC.14.38.17.8.x86.x64"
  ],
  "extensions": []
}
```
I understand that only VS2017/VS2019 manifests are supported, but this doesn't seem to be too complicated of a format?

**Comment by mstorsjo** [comment]
No, that's not the right kind of manifest. It's about the visual studio installer manifest, declaring what packages are available at what url. You probably don't have one from before.

When you run `vsdownload.py` with the option `--save-manifest`, it'll store the current downloaded manifest, so that you can rerun a new install with the exact same files (otherwise the latest manifest on the server might have changed until you'd want to reinstall the same thing again).
