### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'msiextract'

### ISSUE THREAD

**Issue by creeper-0910** [mstorsjo/msvc-wine#51]
```
python3 . /vsdownload.py --dest . /my-msvc
```
I ran the above command and got an error.
The environment is Ubuntu 20.04.
```
Extracting Kits Configuration Installer-x86_en-us.msi
Traceback (most recent call last):
  File "./vsdownload.py", line 619, in <module>
    extractPackages(selected, cache, unpack)
  File "./vsdownload.py", line 531, in extractPackages
    unpackWin10SDK(dir, p["payloads"], dest)
  File "./vsdownload.py", line 515, in unpackWin10SDK
    subprocess.check_call(["msiextract", "-C", dest, srcfile], stdout=log)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msiextract'
```

**Comment by creeper-0910** [comment]
Sorry, the prerequisite package was just not installed correctly.

**Comment by piegamesde** [comment]
For anyone else coming across this issue, it's the Python script requiring the `msiextract` binary from the `msitools` package to be in PATH
