### ISSUE TITLE
Build failed when making VS2017, VS2019 docker image

### ISSUE THREAD

**Issue by changlun65** [mstorsjo/msvc-wine#88]
I would like to build msvc-wine VS2017 (--major 15) with specific MSVC toolchain version (--msvc-version 15.9). But vsdownload.py shows me not find the exact version packages for 15.9 and failed to download packages as below.

How can I build the correct msvc-wine docker image for VS2017 and VS2019?

-----------------------------------
Step 8/9 : RUN PYTHONUNBUFFERED=1 ./vsdownload.py **--major 15 --msvc-version 15.9 --accept-license --dest /opt/msvc** &&     ./install.sh /opt/msvc &&     rm lowercase fixinclude install.sh vsdownload.py &&     rm -rf wrappers
 ---> Running in 03961cbca19f
Fetching https://aka.ms/vs/15/release/channel
Got toplevel manifest for 15.9.56
Loaded installer manifest for 15.9.56
Didn't find exact version packages for 15.9, assuming this is provided by the default/latest version
Selected 306 packages, for a total download size of 1.7 GB, install size of 5.5 GB
Downloading Microsoft.VisualStudio.VC.MSBuild.ARM-15.8.27729.1/payload.vsix (6.9 KB)
Downloading Microsoft.VisualStudio.VC.MSBuild.Base-15.9.28307.1063/payload.vsix (306.7 KB)
Downloading Microsoft.VisualStudio.VC.MSBuild.Base.Resources-15.9.28307.1063/payload.vsix (88.1 KB)
Downloading Microsoft.VisualStudio.VC.MSBuild.X64-15.8.27729.1/payload.vsix (7.1 KB)
Downloading Microsoft.VS.VC.MSBuild.X64.Resources-15.0.26621.2/microsoft.visualstudio.vc.msbuild.x64.resources.vsix (1.3 KB)
Downloading Microsoft.VisualStudio.VC.MSBuild.X86-15.8.27729.1/payload.vsix (6.9 KB)
Downloading Microsoft.Windows.UniversalCRT.Redistributable.Msi-10.0.26624/Universal CRT Redistributable-x86_en-us.msi (304.0 KB)
Downloading Microsoft.Windows.UniversalCRT.Redistributable.Msi-10.0.26624/9126f6ff98d955951fe9323f4444c119.cab (445.0 KB)
Downloading Microsoft.Windows.UniversalCRT.Redistributable.Msi-10.0.26624/948a611cd2aca64b1e5113ffb7b95d5f.cab (610.7 KB)
Downloading Microsoft.Windows.UniversalCRT.Redistributable.Msi-10.0.26624/fef2cfedd6135e0ed85290b83f3682c3.cab (589.3 KB)
Downloading Microsoft.VisualCpp.CRT.Headers-14.16.27033/Microsoft.VisualCpp.CRT.Headers.vsix (2.9 MB)
Downloading Microsoft.VisualCpp.Redist.14-14.16.27033.4-x64/VC_redist.x64.exe (14.6 MB)
Downloading Microsoft.VisualCpp.Redist.14-14.16.27033.4-x86/VC_redist.x86.exe (14.0 MB)
Downloading Microsoft.Windows.UniversalCRT.Msu.7-10.0.26624.1-x64/Windows6.1-KB2999226-x64.msu (1.0 MB)
Downloading Microsoft.Windows.UniversalCRT.Msu.8-10.0.26624-x64/Windows8-RT-KB2999226-x64.msu (1.3 MB)
Downloading Microsoft.Windows.UniversalCRT.Msu.81-10.0.26624-x64/Windows8.1-KB2999226-x64.msu (1.0 MB)
Downloading Microsoft.VisualCpp.RuntimeDebug.14-14.16.27033.1-x64/vc_RuntimeDebug.msi (184.0 KB)
Downloading Microsoft.VisualCpp.RuntimeDebug.14-14.16.27033.1-x64/cab1.cab (8.9 MB)
Downloading Microsoft.VisualCpp.RuntimeDebug.14-14.16.27033.1-x86/vc_RuntimeDebug.msi (180.0 KB)
Downloading Microsoft.VisualCpp.RuntimeDebug.14-14.16.27033.1-x86/cab1.cab (8.5 MB)
Downloading Microsoft.VisualCpp.CRT.Redist.X64-14.16.27033.3/Microsoft.VisualCpp.CRT.Redist.X64.vsix (33.6 MB)
Downloading Microsoft.VisualCpp.CRT.Redist.Resources-14.16.27033/Microsoft.VisualCpp.CRT.Redist.Resources.enu.vsix (1.0 KB)
Downloading Microsoft.VisualCpp.CRT.Redist.X86-14.16.27033.3/Microsoft.VisualCpp.CRT.Redist.X86.vsix (31.8 MB)
Downloading Microsoft.VisualCpp.CRT.Source-14.16.27023/Microsoft.VisualCpp.CRT.Source.vsix (1.0 MB)
Downloading Microsoft.VisualCpp.CRT.x64.Desktop-14.16.27032/Microsoft.VisualCpp.CRT.x64.Desktop.vsix (39.8 MB)
Downloading Microsoft.VisualCpp.CRT.x86.Desktop-14.16.27032/Microsoft.VisualCpp.CRT.x86.Desktop.vsix (36.0 MB)
Downloading Microsoft.VisualCpp.DIA.SDK-14.16.27050/Microsoft.VisualCpp.DIA.SDK.vsix (3.7 MB)
Downloading Microsoft.VisualCpp.Tools.Core.x86-14.16.27027/Microsoft.VisualCpp.Tools.Core.x86.vsix (5.6 KB)
Downloading Microsoft.VisualCpp.Tools.Common.Utils-14.16.27027/Microsoft.VisualCpp.Tools.Common.Utils.vsix (75.9 KB)
Downloading Microsoft.VisualCpp.Tools.Common.Utils.Resources-14.16.27027/Microsoft.VisualCpp.Tools.Common.Utils.Resources.enu.vsix (27.3 KB)
Downloading Microsoft.VisualCpp.Tools.Core.Resources-14.16.27027/Microsoft.VisualCpp.Tools.Core.Resources.enu.vsix (1.0 KB)
Downloading Microsoft.VisualCpp.Tools.HostX86.TargetX86-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX86.vsix (13.5 MB)
Downloading Microsoft.VisualCpp.Tools.HostX86.TargetX86.Resources-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX86.Resources.enu.vsix (199.1 KB)
Downloading Microsoft.VisualCpp.VCTip.hostX86.targetX86-14.16.27050/Microsoft.VisualCpp.VCTip.hostX86.targetX86.vsix (1.0 KB)
Downloading Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix (9.1 MB)
Downloading Microsoft.VisualCpp.Tools.Hostx86.Targetx64.Resources-14.16.27050/Microsoft.VisualCpp.Tools.Hostx86.Targetx64.Resources.enu.vsix (125.6 KB)
Downloading Microsoft.VisualCpp.VCTip.hostX86.targetX64-14.16.27050/Microsoft.VisualCpp.VCTip.hostX86.targetX64.vsix (1.0 KB)
Downloading Microsoft.VisualCpp.CRT.ClickOnce.Msi-14.16.27033/vcpp_crt.redist.clickonce.msi (180.0 KB)
Downloading Microsoft.VisualCpp.CRT.ClickOnce.Msi-14.16.27033/cab1.cab (18.5 KB)
Downloading Microsoft.VisualCpp.CRT.Redist.x64.OneCore.Desktop-14.16.27033/Microsoft.VisualCpp.CRT.Redist.x64.OneCore.Desktop.vsix (1.5 MB)
ConnectionResetError: [Errno 104] Connection reset by peer
Incorrect existing file Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix, removing
Downloading Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix (9.1 MB)
Downloading Microsoft.VisualCpp.CRT.Redist.x86.OneCore.Desktop-14.16.27033/Microsoft.VisualCpp.CRT.Redist.x86.OneCore.Desktop.vsix (1.3 MB)
Downloading Microsoft.VisualCpp.CRT.x64.OneCore.Desktop-14.16.27023/Microsoft.VisualCpp.CRT.x64.OneCore.Desktop.vsix (48.6 MB)
Downloading Microsoft.VisualCpp.CRT.x64.Store-14.16.27032/Microsoft.VisualCpp.CRT.x64.Store.vsix (9.0 MB)
ConnectionResetError: [Errno 104] Connection reset by peer
Incorrect existing file Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix, removing
Downloading Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix (9.1 MB)
Downloading Microsoft.VisualCpp.CRT.x86.OneCore.Desktop-14.16.27023/Microsoft.VisualCpp.CRT.x86.OneCore.Desktop.vsix (44.3 MB)
Downloading Microsoft.VisualCpp.CRT.x86.Store-14.16.27032/Microsoft.VisualCpp.CRT.x86.Store.vsix (8.7 MB)
ConnectionResetError: [Errno 104] Connection reset by peer
Incorrect existing file Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix, removing
Downloading Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix (9.1 MB)
Downloading Microsoft.VisualCpp.PGO.Headers-14.16.27023/Microsoft.VisualCpp.PGO.Headers.vsix (1.8 KB)
Downloading Microsoft.VisualCpp.PGO.X64-14.16.27023/Microsoft.VisualCpp.PGO.X64.vsix (19.3 KB)
Downloading Microsoft.VisualCpp.PGO.X86-14.16.27023/Microsoft.VisualCpp.PGO.X86.vsix (19.2 KB)
Downloading Microsoft.VisualCpp.Premium.Tools.HostX64.TargetX64-14.16.27023-x64/Microsoft.VisualCpp.Premium.Tools.HostX64.TargetX64.vsix (195.0 KB)
Downloading Microsoft.VisualCpp.Premium.Tools.HostX64.TargetX64.Resources-14.16.27023-x64/Microsoft.VisualCpp.Premium.Tools.HostX64.TargetX64.Resources.enu.vsix (29.4 KB)
Downloading Microsoft.VisualCpp.Premium.Tools.HostX64.TargetX86-14.16.27023-x64/Microsoft.VisualCpp.Premium.Tools.HostX64.TargetX86.vsix (99.9 KB)
Downloading Microsoft.VisualCpp.Premium.Tools.HostX64.TargetX86.Resources-14.16.27023-x64/Microsoft.VisualCpp.Premium.Tools.HostX64.TargetX86.Resources.enu.vsix (16.7 KB)
Downloading Microsoft.VisualCpp.Premium.Tools.HostX86.TargetX86-14.16.27023/Microsoft.VisualCpp.Premium.Tools.HostX86.TargetX86.vsix (178.9 KB)
Downloading Microsoft.VisualCpp.Premium.Tools.HostX86.TargetX86.Resources-14.16.27023/Microsoft.VisualCpp.Premium.Tools.HostX86.TargetX86.Resources.enu.vsix (29.3 KB)
ConnectionResetError: [Errno 104] Connection reset by peer
Incorrect existing file Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix, removing
Downloading Microsoft.VisualCpp.Tools.HostX86.TargetX64-14.16.27050/Microsoft.VisualCpp.Tools.HostX86.TargetX64.vsix (9.1 MB)
Downloading Microsoft.VisualCpp.Premium.Tools.HostX86.TargetX64-14.16.27023/Microsoft.VisualCpp.Premium.Tools.HostX86.TargetX64.vsix (91.1 KB)
Downloading Microsoft.VisualCpp.Premium.Tools.Hostx86.Targetx64.Resources-14.16.27023/Microsoft.VisualCpp.Premium.Tools.Hostx86.Targetx64.Resources.enu.vsix (16.6 KB)
Downloading Microsoft.VisualCpp.Tools.HostX64.TargetX64-14.16.27050-x64/Microsoft.VisualCpp.Tools.HostX64.TargetX64.vsix (15.3 MB)
Downloading Microsoft.VisualCpp.Tools.HostX64.TargetX64.Resources-14.16.27050-x64/Microsoft.VisualCpp.Tools.HostX64.TargetX64.Resources.enu.vsix (199.0 KB)
Downloading Microsoft.VisualCpp.VCTip.HostX64.TargetX64-14.16.27050-x64/Microsoft.VisualCpp.VCTip.HostX64.TargetX64.vsix (1.0 KB)
Downloading Microsoft.VisualCpp.Tools.HostX64.TargetX86-14.16.27050-x64/Microsoft.VisualCpp.Tools.HostX64.TargetX86.vsix (10.6 MB)
Downloading Microsoft.VisualCpp.Tools.HostX64.TargetX86.Resources-14.16.27050-x64/Microsoft.VisualCpp.Tools.HostX64.TargetX86.Resources.enu.vsix (125.6 KB)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "./vsdownload.py", line 445, in _downloadPayload
    six.moves.urllib.request.urlretrieve(payload["url"], destname)
  File "/usr/lib/python3.8/urllib/request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./vsdownload.py", line 618, in <module>
    downloadPackages(selected, cache, allowHashMismatch=args.only_download)
  File "./vsdownload.py", line 423, in downloadPackages
    downloaded = sum(task.get() for task in tasks)
  File "./vsdownload.py", line 423, in <genexpr>
    downloaded = sum(task.get() for task in tasks)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ConnectionResetError: [Errno 104] Connection reset by peer
The command '/bin/sh -c PYTHONUNBUFFERED=1 ./vsdownload.py --major 15 --msvc-version 15.9 --accept-license --dest /opt/msvc &&     ./install.sh /opt/msvc &&     rm lowercase fixinclude install.sh vsdownload.py &&     rm -rf wrappers' returned a non-zero code: 1

**Comment by mstorsjo** [comment]
> I would like to build msvc-wine VS2017 (--major 15) with specific MSVC toolchain version (--msvc-version 15.9). But vsdownload.py shows me not find the exact version packages for 15.9

For various reasons with how the manifests are laid out, the latest version in each major version (i.e. 15.9 in `--major 15` and 16.11 in `--major 16`) aren't exposed directly with their version numbers, so you'll get the message "Didn't find exact version packages", but that's pretty much harmless, you'll get what you want anyway.

> and failed to download packages as below.
> 
> How can I build the correct msvc-wine docker image for VS2017 and VS2019?
> 
> File "/usr/lib/python3.8/ssl.py", line 1099, in read return self._sslobj.read(len, buffer) ConnectionResetError: [Errno 104] Connection reset by peer """

This looks like plain network connection errors - I ran the same command `./vsdownload.py --dest ~/msvc2017-15.9 --major 15 --accept-license --msvc-version 15.9` locally, and it worked just fine.
